version: '3.4'

services:
  golacorp.scorekeeper.api:
    image: ${DOCKER_REGISTRY-}golacorpscorekeeperapi
    build:
      context: .
      dockerfile: GolaCorp.ScoreKeeper.Api/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ScoreKeeperDb   
    volumes:    
      - ./db-data/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
  db-data:    